# Generated by Django 5.2.4 on 2025-07-04 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='description',
        ),
    ]
